name: Build and sync to S3
on:
  push:
    branch:
        - master
  workflow_dispatch:

jobs:
  build-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          disable_base64: true
      - name: Build dist
        run: npm run build
      - run: rclone sync --progress dist openbible:static
