name: Build and sync to S3
on:
  push:
    branch:
        - master
        - staging
  workflow_dispatch:

jobs:
  build-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          disable_base64: true
      - run: npm install
      - name: Build dist
        run: npm run build
      - name: copy
        run: |
          case "${{ github.ref_name }}" in
           master) BUCKET="static" ;;
           *) BUCKET="static2" ;;
          esac
          echo "Syncing to bucket $BUCKET"
          rclone copy --size-only --stats-one-line -v --log-file synced --progress dist openbible:$BUCKET
          awk -F': ' '/Copied/ {print "https://'$BUCKET'.openbible.io/"$2}' synced > to_invalidate
      - run: node purge.js to_invalidate
