name: Update staging
on:
  schedule:
    - cron: '30 0 * * *' # give mirrors 30m to sync
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: staging
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          disable_base64: true
# The above will not cascade to the "sync" job.
      - run: deno lint
      - run: deno -A ./build.tsx
      - name: S3 Upload
        run: |
         BUCKET="static2"
          echo "Syncing to bucket $BUCKET"
          rclone copy --size-only --stats-one-line -v --log-file synced --progress dist openbible:$BUCKET
          awk -F': ' '/Copied/ {print "https://'$BUCKET'.openbible.io/"$2}' synced > to_invalidate
      - run: cat to_invalidate
      - run: deno -A ./purge.js to_invalidate
        env:
            CLOUDFLARE_PURGE_KEY: ${{ secrets.CLOUDFLARE_PURGE_KEY }}
