name: Update staging
on:
  schedule:
    - cron: '30 0 * * *' # give mirrors 30m to sync
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: staging
      - run: git submodule update --init
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          disable_base64: true
      - name: Update submodules
        run: git submodule update --remote
      - name: Push submodule updates
        run: |
          git config user.name ci
          git config user.email ci@openbible.io
          git add content
          git commit -m 'Bump submodules'
          git push
# The above will not cascade to the "sync" job.
      - run: npm install
      - name: Build dist
        run: npm run build
      - run: rclone sync --progress dist openbible:static2
